/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.galvanize;

public class App {
    public String getGreeting() {
        return "Hello, Welcome to the bowling scorer application.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
